### ISSUE TITLE
GraphQL Playground DOCS tab stuck in loading

### ISSUE THREAD

**Issue by ccpacillos** [confuser/graphql-constraint-directive#19] opened 2019-08-22 00:51 UTC
I'm not sure what's the problem, but using this makes DOCS tab from GraphQL Playground stuck in loading animation (spinning disk).

**Comment by confuser** [comment] 2019-08-22 20:00
Duplicate of issue #2 where graphql-tools leaks the constraints

**Closed by confuser** 2019-08-22 20:00 UTC
Labels: duplicate
