### ISSUE TITLE
ConstraintString type appeared in graphql schema on the client

### ISSUE THREAD

**Issue by dbuduev** [confuser/graphql-constraint-directive#2] opened 2018-06-08 02:54 UTC
ConstraintString leaked through introspection. Is it by design?
This makes GraphiQL unhappy.
```error
Error: Invalid or incomplete schema, unknown type: ConstraintString. Ensure that a full introspection query is used in order to build a client schema.
```

ConstraintString can be revealed by the following query:
```graphql
query Introspection { 
  __schema {
    types {
      name
      inputFields {
        type {
          name
        }
      }
    }
  }
}
```

**Comment by confuser** [comment] 2018-06-08 14:43
No, certainly not by design. Possibly a bug within `graphql-tools`.

**Comment by yvele** [comment] 2018-06-13 11:03
I have the same problem, and I filled an issue within `graphql-tools` https://github.com/apollographql/graphql-tools/issues/842

**Comment by koresar** [comment] 2018-06-25 07:32
I found a workaround! Omg, took a while.

Add this to your `.graphql` schema file (if you have one though):

```graphql
# Current implementation on graphql-import does not support directives declared outside of the scehma (in node.js code).
# We have to redeclare each directive and type for now.
directive @constraint(
    # String constraints
    minLength: Int
    maxLength: Int
    startsWith: String
    endsWith: String
    notContains: String
    pattern: String
    format: String

    # Number constraints
    min: Int
    max: Int
    exclusiveMin: Int
    exclusiveMax: Int
    multipleOf: Int
) on INPUT_FIELD_DEFINITION

scalar ConstraintString

scalar ConstraintNumber
```

**Comment by koresar** [comment] 2018-06-25 09:35
@confuser hey James,

Quick question. In this article 
https://dev-blog.apollodata.com/reusable-graphql-schema-directives-131fb3a177d1
they suggest to override `field.resolver`. See `AuthDirective` example.

Any reason you went by creating the new `ConstraintString` type class?

**Comment by confuser** [comment] 2018-06-25 09:42
@koresar The recommendation seemed to be using custom scalar types to achieve this, rather than overriding the resolver function https://www.apollographql.com/docs/graphql-tools/schema-directives.html#Enforcing-value-restrictions I'm certainly open to switching to a resolver function instead if it eases pains people are facing.

**Comment by koresar** [comment] 2018-06-25 10:39
Frankly, I tried this:
```js
class MyConstraintDirective extends SchemaDirectiveVisitor {
    static getDirectiveDeclaration(directiveName, schema) {
        return new GraphQLDirective({
            name: directiveName,
            locations: [DirectiveLocation.INPUT_FIELD_DEFINITION]
        });
    }

    visitInputFieldDefinition(field, details) {
        field.resolve = async function(...args) {
            throw new Error("not valid");
        };
    }
}
```
But for some reason the `resolve` is never hit. The `visitInputFieldDefinition` is executed for every field though.

So, not sure what to do frankly.

**Comment by koresar** [comment] 2018-06-25 11:49
I debugged a little. TL;DR: The `makeExecutableSchema` does not replace the directive object in schema.

* The `graphql-import` people tell you to "declare the `@constraint` scalar in .graphql file". It effectively creates a directive object in schema. Which is right thing to do IMO. My IDE stops complaining about "undeclared directive!".
* The `makeExecutableSchema` accepts the `schemaDirectives` and applies the schema visitor to them. But it does not replace the previously declared directive generated by `graphql-import`.

Here is a screenshot. I made it in node.js debugger one step before exiting the `makeExecutableSchema`. Basically, that `schema` variable is what I get.
![image](https://user-images.githubusercontent.com/1622575/41848605-4fc52d30-78c1-11e8-9629-ef07110d4640.png)

@confuser where should I rant about it next? In **apollographql/graphql-tools** ? :)

**Comment by koresar** [comment] 2018-07-04 10:23
I solved the problem. The `@constaint` is fully working. What I did:
* ditched the `graphql-yoga` and the `graphql-import` with it.

Turns our Prism and Apollo packages are not fully compatible.

**Comment by confuser** [comment] 2018-07-04 10:47
@koresar Interesting, so the new `apollo-server` v2 solves the issue with schema stitching without any changes here? I presume it doesn't resolve the problem you mentioned earlier around overwriting the resolver function instead of using custom scalars?

**Comment by koresar** [comment] 2018-07-05 01:42
Sorry, should have mentioned. There were actually a lot of changes.

I had to rewrite schema stitching.
* Removed all the Prisma's `#import` statements, and
* used Apollo's [`mergeSchema()`](https://www.apollographql.com/docs/apollo-server/v2/api/graphql-tools.html#mergeSchemas) JS function.

It did solve all the problems I had.

The high level solution: do not use Prisma and Apollo packages in the same project. They are often incompatible.

**Comment by koresar** [comment] 2018-07-06 06:15
Ok. I was wrong. Again. No, I did not fix all the problems I have. Even Apollo Stack v2 didn't help.

Currently:
* Either directive works, but introspection doesn't.
* Or directive does not work, but introspection works.

If I follow the README.md instructions then I get this error in the GraphQL Playground console: `Invalid or incomplete schema, unknown type: ConstraintString`.

If I add `scalar ConstraintString` to my schema then the directive stops working.

I believe that official Apollo docs are wrong: https://www.apollographql.com/docs/apollo-server/v2/features/creating-directives.html#Enforcing-value-restrictions
This way of implementing it does not work.

**Comment by koresar** [comment] 2018-07-06 06:35
I've reported the issue here: https://github.com/apollographql/apollo-server/issues/1303

@confuser It is so frustrating. Do you know any other ways the directive can be implemented? I am ready to do it myself. Just need an idea.

**Comment by confuser** [comment] 2018-07-09 16:01
@koresar Were you not able to overwrite the resolver function at all? If not, there is one other way, but it was deprecated in favour of the current approach, so I'd be hesitant of using it... [directiveResolvers](https://www.apollographql.com/docs/graphql-tools/directive-resolvers.html)

**Comment by koresar** [comment] 2018-07-10 05:43
I tried directiveResolvers. Exactly the same issue - the directive resolver function is never executed.
https://github.com/apollographql/apollo-server/issues/1303#issuecomment-403700824

I tried all kind of approaches (including reimplementing the directive myself). Nothing works.

Basically, the directive is in a non-working state atm.

**Comment by confuser** [comment] 2018-07-10 08:49
Strange... I have a project that uses directiveResolvers as a form of ACL and it works. I'll find some time and investigate what's happening.

**Comment by koresar** [comment] 2018-07-10 12:36
Which graphql-tools version it uses?
Also, is your directive for `input` type(s)?

**Comment by FrankSandqvist** [comment] 2018-07-11 12:08
I'm currently having exactly the same issue. Super frustrating. 

Haven't had any success yet. Switched to Apollo server 2 from Yoga

**Comment by FrankSandqvist** [comment] 2018-07-11 12:09
I had an idea of perhaps doing MakeExecutableSchema twice and then combining them, getting the generated validated scalars from the first one into the other one

**Comment by koresar** [comment] 2018-07-12 05:43
Hey @FrankSandqvist 
The `ApolloServer` constructor accepts only one schema.

How did you attach these two schemas to Playground and to the API?

**Comment by FrankSandqvist** [comment] 2018-07-12 06:05
I pass in the merged schema finalSchema

```
const server = new ApolloServer({
  schema: finalSchema,
  resolvers,
  context: async ({ req }) => ({
    db: new Prisma({
      endpoint: 'http://localhost:4466', // the endpoint of the Prisma API
      debug: true, // log all GraphQL queries & mutations sent to the Prisma API
      secret: process.env.PRISMA_SECRET, // only needed if specified in `database/prisma.yml`,
      // fragmentReplacements: replacements
    }),
    requestUser: await verifyUserEmailFromToken(req.headers.authorization)
  })
});
```

**Comment by FrankSandqvist** [comment] 2018-07-12 07:44
Of course this still doesn't solve the problem that the scalars are public.

For example StringWithMaxLength50WithMinLength5ThatConformsToEMAIL

**Comment by koresar** [comment] 2018-07-12 23:38
Dear @FrankSandqvist 

People like you deserve monuments erected. 

![image](https://user-images.githubusercontent.com/1622575/42664870-6dd1bd62-8680-11e8-80de-5329931f8e92.png)

(That's my way of saying  "thank you, it works").

**Comment by FrankSandqvist** [comment] 2018-07-13 07:02
Hahah, that's awesome! I've always wanted a thinking Shakespeare ape monument in my name 😄

**Comment by pathikdevani** [comment] 2018-08-17 11:35
Any solution or update on this?

**Comment by confuser** [comment] 2018-08-17 11:36
Unfortunately not, dependent on apollo

**Comment by arvi** [comment] 2018-09-11 06:51
I am also waiting for a solution to this :smile:

**Comment by gerwinbrunner** [comment] 2018-12-11 16:42
@FrankSandqvist Could you share how your Scalar files that you read in look like?

**Comment by padenj** [comment] 2019-04-30 06:52
I ran across this issue trying to solve a similar issue in a custom directive I created.  My situation was slightly different, but I came up with a solution that could work for this issue as well.  It would require an update to the directive and I'm not sure how/if it would affect non-Apollo users.   
The issue is that a new type is being created in the directive schema visitor, but the type is not being added to the schema type map.  For example, https://github.com/confuser/graphql-constraint-directive/blob/master/index.js#L54.  If the type is not added to the schema type map, then the above mentioned error "Incomplete or Invalid schema..." will occur when Playground introspects the schema.  The following could be a possible solution.  This example could be simplified since the new type is known to be either ConstraintStringType or ConstraintNumberType, but I left it a bit more generic for anyone else who might run across this issue.  Note, isNamedType and isWrappingType is imported from 'graphql'.

A possible solution could be to modify the wrapType function:
`wrapType (field) {
    const fieldName = field.astNode.name.value

    if (field.type instanceof GraphQLNonNull && field.type.ofType === GraphQLString) {
      field.type = new GraphQLNonNull(new ConstraintStringType(fieldName, field.type.ofType, this.args))
    } else if (field.type === GraphQLString) {
      field.type = new ConstraintStringType(fieldName, field.type, this.args)
    } else if (field.type instanceof GraphQLNonNull && (field.type.ofType === GraphQLFloat || field.type.ofType === GraphQLInt)) {
      field.type = new GraphQLNonNull(new ConstraintNumberType(fieldName, field.type.ofType, this.args))
    } else if (field.type === GraphQLFloat || field.type === GraphQLInt) {
      field.type = new ConstraintNumberType(fieldName, field.type, this.args)
    } else {
      throw new Error(`Not a scalar type: ${field.type}`)
    }

   const typeMap = this.schema.getTypeMap();
   let type = field.type;

    if (isWrappingType(type)) {
           type = type.ofType;
    }

    if (isNamedType(type) && !typeMap[type.name]) {
          typeMap[type.name] = type;
    }
  }`

**Comment by TienHuong** [comment] 2019-08-17 15:53
@FrankSandqvist Could you show your scalar files?
I'm facing this issue. Having other solutions for this?

**Comment by koresar** [comment] 2020-01-23 00:53
Hi there. Here is a fresh out of the press new (forked) constraint directive. It's using the idea suggested by @padenj 
https://github.com/alexanderVu/apollo-server-constraint-directive

**Comment by julianomqs** [comment] 2020-01-24 01:28
@padenj code does not work if you have the `constraint`directive in more than one field of the input, like this:

```graphql
input CreateUserInput {
  login: String! @constraint(minLength: 1)
  password: String! @constraint(minLength: 1)
}
```
because of this if:

```javascript
if (isNamedType(type) && !typeMap[type.name]) {
  typeMap[type.name] = type;
}
```

Steps of directive resolution:

1) When the `login` field is processed by the directive visitor a new `ConstraintString` scalar is created with `fieldName` value being `login` and set in the field type. 

2) In the `if` above the type created for `login` field is assigned to the key `ConstraintString` in the `typeMap`, in another words becoming the global resolver for `ConstraintString` scalar type.

3) When the `password` field is processed by the directive visitor a new `ConstraintString` scalar is created with `fieldName` value being `password` and set in the field type. 

4) The `if` above is not executed.

The `login` and `password` field will not use the types created for them to resolve their code, but they will use the first type put in the map (`login` type) instead.

Apparently scalar types in Apollo (and/or GraphQL) can have only one resolver for a scalar type. Theorically it makes sense, because any field of the same type must be serialized or parsed in the same way.

If you don't add @padenj code, the directives will work but not the introspection, and we return to the main problem of this issue.

**Comment by RedHotMan** [comment] 2020-03-13 15:17
@julianomqs creating a specific scalar type using the fieldName per example would be a solution. 
```javascript
class StringConstraintType extends GraphQLScalarType {
  constructor(fieldName, type, args) {
    super({
      name: `StringConstraint${fieldName.toUpperCase()}`,
      serialize(value) {
        value = type.serialize(value);
        validate(fieldName, value, args);
        return value;
      },
      parseValue(value) {
        value = type.parseValue(value);
        validate(fieldName, value, args);
        return value;
      },
      parseLiteral(ast) {
        const value = type.parseLiteral(ast);
        validate(fieldName, value, args);
        return value;
      }
    });
  }
}
```

**Comment by cmartin81** [comment] 2020-05-12 18:46
> Woot! Found a workaround.
> 
> First make an executable schema for the scalar schema, and then merge that with the rest.
> 
> It's hacky and I don't like it, but at least I can move on now.
> 
> ```
> const scalars = makeExecutableSchema({
>   typeDefs: readFileSync(path/to/scalars).toString()
> });
> 
> const schema = makeExecutableSchema({
>   resolvers,
>   typeDefs,
>   schemaDirectives: {
>     identifier: IdentifierDirective,
>     access: AccessDirective,
>     validate: ValidateDirective
>   }
> });
> 
> const finalSchema = mergeSchemas({ schemas: [scalars, schema] });
> ```

This works for now! Thanks.
I did almost the same use this
`const scalars = makeExecutableSchema({
  typeDefs: `
  scalar ValidateString
  scalar ValidateNumber
`,
});`

**Closed** 2020-05-21 19:40 UTC
Labels: bug
