### ISSUE TITLE
Unable to apply constraints to a new Apollo server project

### ISSUE THREAD

**Issue by gpaluk** [confuser/graphql-constraint-directive#52] opened 2020-12-30 01:48 UTC
I am getting back no errors when I apply constraints to my new Apollo server project. I have created a minimal project to illustrate the point at:

https://github.com/gpaluk/apollo-graphql-mfp

When using the following GraphQL query in the playground, the entity gets created which is undesired:

```
mutation {
  CreateUser(userRole:"admin", username:"a", email:"a")
  {
    userRole
    username
    email
  }
}
```

**Comment by confuser** [comment] 2020-12-31 14:56
It looks like you're using `neo4j-graphql-js` instead of `graphql-tools` `makeExecutableSchema` function. I'm not familiar with it nor has this module been tested against it. Would suggest opening an issue with the author, happy to accept a PR to add compatibility.

**Comment by gpaluk** [comment] 2021-01-09 14:02
During ongoing discussions over at: https://github.com/neo4j-graphql/neo4j-graphql-js/issues/562 - I have been testing around this library and have a question about the working ideas of this library. Entities seem to be added into the database regardless of whether or not they are valid?!.. Then only if one is to return the field in the GraphQL statement does the check occur and return an error response?! I'm quite confused to implementation concepts as this doesn't at all correlate to the way that validation is usually implemented (To guard database entries for invalid data). Is there a setting that I'm missing that makes this work as I think most people would assume? Many thanks

**Comment by gpaluk** [comment] 2021-01-09 14:08
I have tested just the @unique annotation from `neo4j-graphql-js` and that guards against the insertion of entities into the database as expected.

**Comment by confuser** [comment] 2021-01-09 14:51
The issue you're describing is still likely caused by `neo4j-graphql-js`. I've checked your example repo, and within the schema I can't see any `input`s being defined, nor can I see where your mutation queries are being defined either?

```
type Mutation {
  createBook(input: BookInput): Book
}
input BookInput {
  title: String! @constraint(minLength: 5, format: "email")
}
```

**Comment by gpaluk** [comment] 2021-01-10 20:40
Hi @confuser - Actually, everything is autogenerated by `makeAugmentedSchema`. This should be clear if you build and head to the playground. All of the schema is described in the relevant tab as usual.

**Comment by confuser** [comment] 2021-03-09 12:36
@gpaluk closing as it appears to be neo4j specific based on https://github.com/neo4j-graphql/neo4j-graphql-js/issues/562

**Closed by confuser** 2021-03-09 12:36 UTC
Labels: question
